### ISSUE TITLE
Besoin d'un peu d'aide pour comprendre

### ISSUE THREAD

**Issue by Nalbrespic** [darkanakin41/table-bundle#4]
Hello @darkanakin41,

Maintenant tout marche nickel en local, mais j'ai juste besoin d'un peu d'aide pour comprendre ce bundle Table, savoir comment il se construit.

// Image supprimé à cause des données personnelles
les commandes sont classées par Bl (ordre chronologique) du coup on a la commande la plus ancienne en premier.. comment je peux changer cette ordre ??

![image](https://user-images.githubusercontent.com/66831433/92580345-8b9fb980-f28e-11ea-83ea-d88c970b2c46.png)

est ce ici ??

Merci d'avance pour ton aide ;)

**Comment by darkanakin41** [comment]
@Nalbrespic, dans la classe AbstractTable dont hérite tous les tableau, il y a une méthode setDefaultSort(array $fields)

Le paramètre Fields accèpte un tableau clé => valeur où :
* clé est le nom du champs
* order est le tri a appliquer (ASC ou DESC) 

Exemple dans ton projet : Ligne 30 du fichier app/src/Table/Common/ArticleTable.php

Par contre attention aux captures d'écran et des données RGPD

**Comment by Nalbrespic** [comment]
Pierre,

Merci pour ta réponse, j’y vois un peu plus claire !
Je supprime l’issue de suite par rapport aux captures d’écran.
